# This file was autogenerated and should not be edited
from .base import MetadataBase


class MetadataV1(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        AIDelay,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: list[tuple[float, float, float, float]] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.AIDelay: int = AIDelay
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.FileLength: int = FileLength


class MetadataV2(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        AIDelay,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: list[tuple[float, float, float, float]] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.AIDelay: int = AIDelay
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.FileLength: int = FileLength


class MetadataV3(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        AIDelay,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMShiftX,
        SEMShiftY,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: list[tuple[float, float, float, float]] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.AIDelay: int = AIDelay
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMShiftX: float = SEMShiftX
        self.SEMShiftY: float = SEMShiftY
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.FileLength: int = FileLength


class MetadataV4(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        Detmin,
        Detmax,
        DecimatingFactor,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMShiftX,
        SEMShiftY,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: list[tuple[float, float, float, float]] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.Detmin: float = Detmin
        self.Detmax: float = Detmax
        self.DecimatingFactor: int = DecimatingFactor
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMShiftX: float = SEMShiftX
        self.SEMShiftY: float = SEMShiftY
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.FileLength: int = FileLength


class MetadataV5(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        Detmin,
        Detmax,
        DecimatingFactor,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMShiftX,
        SEMShiftY,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        MillingXResolution,
        MillingYResolution,
        MillingXSize,
        MillingYSize,
        MillingULAng,
        MillingURAng,
        MillingLineTime,
        FIBFOV,
        MillingLinesPerImage,
        MillingPIDOn,
        MillingPIDMeasured,
        MillingPIDTarget,
        MillingPIDTargetSlope,
        MillingPIDP,
        MillingPIDI,
        MillingPIDD,
        MachineID,
        SEMSpecimenI,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: list[tuple[float, float, float, float]] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.Detmin: float = Detmin
        self.Detmax: float = Detmax
        self.DecimatingFactor: int = DecimatingFactor
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMShiftX: float = SEMShiftX
        self.SEMShiftY: float = SEMShiftY
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.MillingXResolution: int = MillingXResolution
        self.MillingYResolution: int = MillingYResolution
        self.MillingXSize: float = MillingXSize
        self.MillingYSize: float = MillingYSize
        self.MillingULAng: float = MillingULAng
        self.MillingURAng: float = MillingURAng
        self.MillingLineTime: float = MillingLineTime
        self.FIBFOV: float = FIBFOV
        self.MillingLinesPerImage: int = MillingLinesPerImage
        self.MillingPIDOn: int = MillingPIDOn
        self.MillingPIDMeasured: int = MillingPIDMeasured
        self.MillingPIDTarget: float = MillingPIDTarget
        self.MillingPIDTargetSlope: float = MillingPIDTargetSlope
        self.MillingPIDP: float = MillingPIDP
        self.MillingPIDI: float = MillingPIDI
        self.MillingPIDD: float = MillingPIDD
        self.MachineID: bytes = MachineID
        self.SEMSpecimenI: float = SEMSpecimenI
        self.FileLength: int = FileLength


class MetadataV6(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        Detmin,
        Detmax,
        DecimatingFactor,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMShiftX,
        SEMShiftY,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        MillingXResolution,
        MillingYResolution,
        MillingXSize,
        MillingYSize,
        MillingULAng,
        MillingURAng,
        MillingLineTime,
        FIBFOV,
        MillingLinesPerImage,
        MillingPIDOn,
        MillingPIDMeasured,
        MillingPIDTarget,
        MillingPIDTargetSlope,
        MillingPIDP,
        MillingPIDI,
        MillingPIDD,
        MachineID,
        SEMSpecimenI,
        Temperature,
        FaradayCupI,
        FIBSpecimenI,
        BeamDump1I,
        SEMSpecimenICurrent,
        MillingYVoltage,
        FocusIndex,
        FIBSliceNum,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: list[tuple[float, float, float, float]] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.Detmin: float = Detmin
        self.Detmax: float = Detmax
        self.DecimatingFactor: int = DecimatingFactor
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMShiftX: float = SEMShiftX
        self.SEMShiftY: float = SEMShiftY
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.MillingXResolution: int = MillingXResolution
        self.MillingYResolution: int = MillingYResolution
        self.MillingXSize: float = MillingXSize
        self.MillingYSize: float = MillingYSize
        self.MillingULAng: float = MillingULAng
        self.MillingURAng: float = MillingURAng
        self.MillingLineTime: float = MillingLineTime
        self.FIBFOV: float = FIBFOV
        self.MillingLinesPerImage: int = MillingLinesPerImage
        self.MillingPIDOn: int = MillingPIDOn
        self.MillingPIDMeasured: int = MillingPIDMeasured
        self.MillingPIDTarget: float = MillingPIDTarget
        self.MillingPIDTargetSlope: float = MillingPIDTargetSlope
        self.MillingPIDP: float = MillingPIDP
        self.MillingPIDI: float = MillingPIDI
        self.MillingPIDD: float = MillingPIDD
        self.MachineID: bytes = MachineID
        self.SEMSpecimenI: float = SEMSpecimenI
        self.Temperature: float = Temperature
        self.FaradayCupI: float = FaradayCupI
        self.FIBSpecimenI: float = FIBSpecimenI
        self.BeamDump1I: float = BeamDump1I
        self.SEMSpecimenICurrent: float = SEMSpecimenICurrent
        self.MillingYVoltage: float = MillingYVoltage
        self.FocusIndex: float = FocusIndex
        self.FIBSliceNum: int = FIBSliceNum
        self.FileLength: int = FileLength


class MetadataV7(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        Detmin,
        Detmax,
        DecimatingFactor,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMShiftX,
        SEMShiftY,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        MillingXResolution,
        MillingYResolution,
        MillingXSize,
        MillingYSize,
        MillingULAng,
        MillingURAng,
        MillingLineTime,
        FIBFOV,
        MillingLinesPerImage,
        MillingPIDOn,
        MillingPIDMeasured,
        MillingPIDTarget,
        MillingPIDTargetSlope,
        MillingPIDP,
        MillingPIDI,
        MillingPIDD,
        MachineID,
        SEMSpecimenI,
        Temperature,
        FaradayCupI,
        FIBSpecimenI,
        BeamDump1I,
        SEMSpecimenICurrent,
        MillingYVoltage,
        FocusIndex,
        FIBSliceNum,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: tuple[
            tuple[float, float, float, float], tuple[float, float, float, float]
        ] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.Detmin: float = Detmin
        self.Detmax: float = Detmax
        self.DecimatingFactor: int = DecimatingFactor
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMShiftX: float = SEMShiftX
        self.SEMShiftY: float = SEMShiftY
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.MillingXResolution: int = MillingXResolution
        self.MillingYResolution: int = MillingYResolution
        self.MillingXSize: float = MillingXSize
        self.MillingYSize: float = MillingYSize
        self.MillingULAng: float = MillingULAng
        self.MillingURAng: float = MillingURAng
        self.MillingLineTime: float = MillingLineTime
        self.FIBFOV: float = FIBFOV
        self.MillingLinesPerImage: int = MillingLinesPerImage
        self.MillingPIDOn: int = MillingPIDOn
        self.MillingPIDMeasured: int = MillingPIDMeasured
        self.MillingPIDTarget: float = MillingPIDTarget
        self.MillingPIDTargetSlope: float = MillingPIDTargetSlope
        self.MillingPIDP: float = MillingPIDP
        self.MillingPIDI: float = MillingPIDI
        self.MillingPIDD: float = MillingPIDD
        self.MachineID: bytes = MachineID
        self.SEMSpecimenI: float = SEMSpecimenI
        self.Temperature: float = Temperature
        self.FaradayCupI: float = FaradayCupI
        self.FIBSpecimenI: float = FIBSpecimenI
        self.BeamDump1I: float = BeamDump1I
        self.SEMSpecimenICurrent: float = SEMSpecimenICurrent
        self.MillingYVoltage: float = MillingYVoltage
        self.FocusIndex: float = FocusIndex
        self.FIBSliceNum: int = FIBSliceNum
        self.FileLength: int = FileLength


class MetadataV8(MetadataBase):
    def __init__(
        self,
        FileMagicNum,
        FileVersion,
        FileType,
        SWdate,
        TimeStep,
        ChanNum,
        EightBit,
        Scaling,
        XResolution,
        YResolution,
        Oversampling,
        ZeissScanSpeed,
        ScanRate,
        FramelineRampdownRatio,
        Xmin,
        Xmax,
        Detmin,
        Detmax,
        DecimatingFactor,
        AI1,
        AI2,
        AI3,
        AI4,
        Notes,
        DetA,
        DetB,
        DetC,
        DetD,
        Mag,
        PixelSize,
        WD,
        EHT,
        SEMApr,
        HighCurrent,
        SEMCurr,
        SEMRot,
        ChamVac,
        GunVac,
        SEMShiftX,
        SEMShiftY,
        SEMStiX,
        SEMStiY,
        SEMAlnX,
        SEMAlnY,
        StageX,
        StageY,
        StageZ,
        StageT,
        StageR,
        StageM,
        BrightnessA,
        ContrastA,
        BrightnessB,
        ContrastB,
        Mode,
        FIBFocus,
        FIBProb,
        FIBCurr,
        FIBRot,
        FIBAlnX,
        FIBAlnY,
        FIBStiX,
        FIBStiY,
        FIBShiftX,
        FIBShiftY,
        MillingXResolution,
        MillingYResolution,
        MillingXSize,
        MillingYSize,
        MillingULAng,
        MillingURAng,
        MillingLineTime,
        FIBFOV,
        MillingLinesPerImage,
        MillingPIDOn,
        MillingPIDMeasured,
        MillingPIDTarget,
        MillingPIDTargetSlope,
        MillingPIDP,
        MillingPIDI,
        MillingPIDD,
        MachineID,
        SEMSpecimenI,
        Temperature,
        FaradayCupI,
        FIBSpecimenI,
        BeamDump1I,
        SEMSpecimenICurrent,
        MillingYVoltage,
        FocusIndex,
        FIBSliceNum,
        BeamDump2I,
        MillingI,
        FileLength,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.FileMagicNum: int = FileMagicNum
        self.FileVersion: int = FileVersion
        self.FileType: int = FileType
        self.SWdate: bytes = SWdate
        self.TimeStep: float = TimeStep
        self.ChanNum: int = ChanNum
        self.EightBit: int = EightBit
        self.Scaling: tuple[
            tuple[float, float, float, float], tuple[float, float, float, float]
        ] = Scaling
        self.XResolution: int = XResolution
        self.YResolution: int = YResolution
        self.Oversampling: int = Oversampling
        self.ZeissScanSpeed: int = ZeissScanSpeed
        self.ScanRate: float = ScanRate
        self.FramelineRampdownRatio: float = FramelineRampdownRatio
        self.Xmin: float = Xmin
        self.Xmax: float = Xmax
        self.Detmin: float = Detmin
        self.Detmax: float = Detmax
        self.DecimatingFactor: int = DecimatingFactor
        self.AI1: int = AI1
        self.AI2: int = AI2
        self.AI3: int = AI3
        self.AI4: int = AI4
        self.Notes: bytes = Notes
        self.DetA: bytes = DetA
        self.DetB: bytes = DetB
        self.DetC: bytes = DetC
        self.DetD: bytes = DetD
        self.Mag: float = Mag
        self.PixelSize: float = PixelSize
        self.WD: float = WD
        self.EHT: float = EHT
        self.SEMApr: int = SEMApr
        self.HighCurrent: int = HighCurrent
        self.SEMCurr: float = SEMCurr
        self.SEMRot: float = SEMRot
        self.ChamVac: float = ChamVac
        self.GunVac: float = GunVac
        self.SEMShiftX: float = SEMShiftX
        self.SEMShiftY: float = SEMShiftY
        self.SEMStiX: float = SEMStiX
        self.SEMStiY: float = SEMStiY
        self.SEMAlnX: float = SEMAlnX
        self.SEMAlnY: float = SEMAlnY
        self.StageX: float = StageX
        self.StageY: float = StageY
        self.StageZ: float = StageZ
        self.StageT: float = StageT
        self.StageR: float = StageR
        self.StageM: float = StageM
        self.BrightnessA: float = BrightnessA
        self.ContrastA: float = ContrastA
        self.BrightnessB: float = BrightnessB
        self.ContrastB: float = ContrastB
        self.Mode: int = Mode
        self.FIBFocus: float = FIBFocus
        self.FIBProb: int = FIBProb
        self.FIBCurr: float = FIBCurr
        self.FIBRot: float = FIBRot
        self.FIBAlnX: float = FIBAlnX
        self.FIBAlnY: float = FIBAlnY
        self.FIBStiX: float = FIBStiX
        self.FIBStiY: float = FIBStiY
        self.FIBShiftX: float = FIBShiftX
        self.FIBShiftY: float = FIBShiftY
        self.MillingXResolution: int = MillingXResolution
        self.MillingYResolution: int = MillingYResolution
        self.MillingXSize: float = MillingXSize
        self.MillingYSize: float = MillingYSize
        self.MillingULAng: float = MillingULAng
        self.MillingURAng: float = MillingURAng
        self.MillingLineTime: float = MillingLineTime
        self.FIBFOV: float = FIBFOV
        self.MillingLinesPerImage: int = MillingLinesPerImage
        self.MillingPIDOn: int = MillingPIDOn
        self.MillingPIDMeasured: int = MillingPIDMeasured
        self.MillingPIDTarget: float = MillingPIDTarget
        self.MillingPIDTargetSlope: float = MillingPIDTargetSlope
        self.MillingPIDP: float = MillingPIDP
        self.MillingPIDI: float = MillingPIDI
        self.MillingPIDD: float = MillingPIDD
        self.MachineID: bytes = MachineID
        self.SEMSpecimenI: float = SEMSpecimenI
        self.Temperature: float = Temperature
        self.FaradayCupI: float = FaradayCupI
        self.FIBSpecimenI: float = FIBSpecimenI
        self.BeamDump1I: float = BeamDump1I
        self.SEMSpecimenICurrent: float = SEMSpecimenICurrent
        self.MillingYVoltage: float = MillingYVoltage
        self.FocusIndex: float = FocusIndex
        self.FIBSliceNum: int = FIBSliceNum
        self.BeamDump2I: float = BeamDump2I
        self.MillingI: float = MillingI
        self.FileLength: int = FileLength


VERSION_REGISTRY = {
    {1: MetadataV1},
    {2: MetadataV2},
    {3: MetadataV3},
    {4: MetadataV4},
    {5: MetadataV5},
    {6: MetadataV6},
    {7: MetadataV7},
    {8: MetadataV8},
}
