on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          pip install pre-commit
          pre-commit install
      - run: make lint

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install -U pip wheel setuptools
          pip install -r requirements.txt
        name: Install dependencies
      - run: pip install '.[all]'
        name: Install package
      - run: pytest --verbose

  deploy-package:
    runs-on: ubuntu-18.04
    needs: [lint, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install build
      - run: python -m build --sdist --wheel -o dist/ .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
